# cation.yml
name: Astro Action
description: Run astro CLI commands
inputs:
  version:
    required: false
    default: latest
    description: "What version of the action should be ran?"
  command:  
    description: What commands should we run?
    required: true
  mountpoint: 
    description: Where's your Airflow project?
    default: .
    required: false
  astro_key_id:
    required: true
    description: API key for Astronomer
  astro_key_secret:
    required: true
    description: Secret key for Astronomer

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'

runs:
  using: composite
  steps:
    - run: echo ${{ inputs.github_secret }} | docker login -u ${{ github.actor }} --password-stdin
      shell: bash
    - run: |
        docker run -v ${{ inputs.mountpoint }}:/workspace \
          -e ASTRONOMER_KEY_ID=${{ inputs.astro_key_id }} \
          -e ASTRONOMER_KEY_SECRET=${{ inputs.astro_key_secret }} \
          edwardofclt/astro-action:${{ inputs.version }} ${{ inputs.command }}
      shell: bash