name: Astro Action
description: Run astro CLI commands
inputs:
  version:
    required: false
    default: latest
    description: "What version of the action should be ran?"
  command:  
    description: What commands should we run?
    required: true
  mountpoint: 
    description: Where's your Airflow project?
    default: .
    required: false

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'

runs:
  using: 'docker'
  image: Dockerfile
  args:
    - -v ${{ inputs.mountpoint }}:/workspace
    - --entrypoint ${{ inputs.command }}
  