name: Release Version
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * MON
  workflow_dispatch: 
    inputs:
      image_version:
        required: true
        description: What version of the container should be built?

permissions:
  packages: write
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        if: ${{ inputs.image_version }} == ""
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                releases(first:1) {
                  nodes {
                    name
                  }
                }
              }
            }
          owner: astronomer
          repo: astro-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: astro_version
        run: |
          echo 'version=${{ inputs.image_version || fromJSON(steps.get_latest_release.outputs.data).repository.releases.nodes[0].name }}' >> $GITHUB_OUTPUT

      - run: |
          docker build --build-arg ASTRO_VERSION=${{ steps.astro_version.outputs.version }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f ./.github/workflows/Dockerfile .
          docker image tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.astro_version.outputs.version }}
          docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}