name: Test the Action

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: edwardofclt/astro-action@05c8d50aedde321c3e328679503e44c5ec0a0e4e
        with:
          astro_key_id: asdf
          astro_key_secret: asdf