name: Test the Action

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./action.yml
        with:
          astro_key_id: asdf
          astro_key_secret: asdf
          github_secret: ${{ secrets.GITHUB_TOKEN }}