name: Test the Action

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    container: edwardofclt/astro-action@lastest
    steps:
      - uses: actions/checkout@v3
      - run: astro --version