name: Test the Action

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/edwardofclt/astro-action@latest
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v3
      - run: astro --version