name: Test the Action

on:
  workflow_dispatch: 
    inputs:
      image_version:
        default: latest
        description: What version of the container should run?

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/edwardofclt/astro-action:latest
    steps:
      - uses: actions/checkout@v3
      - run: astro version